### Emma Klemets, 260775167   
All my work, code, output and written answers are in this notebook.

In [3]:
#for interactive plots

# %matplotlib
# %matplotlib inline
# %matplotlib notebook

In [4]:
import numpy as np
import matplotlib

#for pop out plots - windows
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
import time
import matplotlib.cm as cm

Make a 3-D nbody code that calculates the forces by computing the potential, where the potential is found by convolving the density with the (softened) potential from a single particle. The acceleration is then found by taking the gradient of the potential. You will probably wish to use a leapfrog solver with fixed timestep.

In [21]:
#nbody_class.py
class Particles:
    def __init__(self,x,v,m):
        self.x=x.copy()
        self.v=v.copy()
        try:
            self.m=m.copy()
        except:
            self.m=m
        self.f=np.empty(x.shape)
        self.n=self.x.shape[0]
        
    def get_forces(self):
        self.f[:]=0
        for i in range(self.n):
            for j in range(self.n):
                if i!=j:
                    dx=-self.x[i,:]+self.x[j,:]
                    drsqr=np.sum(dx**2)
                    r=np.sqrt(drsqr)
                    self.f[i,:]=self.f[i,:]+dx*self.m[j]/(r*drsqr)
                    
    def take_step_simple(self,dt):
        self.get_forces()
        self.x=self.x+dt*self.v
        self.v=self.v+dt*self.f
   

In [22]:
n=10
x=np.random.randn(n,2)
v=np.random.randn(n,2)*0
m=np.ones(n)
parts=Particles(x,v,m)
dt=0.1

colors = cm.rainbow(np.linspace(0, 1, n))

fig, ax = plt.subplots()

for i in range(100):
    print('step ',i)
    print(parts.x)

    for n_i in range(n):
        ax.scatter(parts.x[n_i][0], parts.x[n_i][1], color=colors[n_i])
#         ax.scatter(parts.x[n][0], parts.x[n_i][1], color='g')
#     time.sleep(0.1)
    ax.set_title("frame {}".format(i))

    plt.pause(0.01)

    parts.take_step_simple(dt)
fig.show()
# line.remove()

step  0
[[-0.42501613 -0.25047283]
 [-1.70571528  0.1886584 ]
 [ 1.74723308 -0.24772639]
 [-1.04767373  0.08129321]
 [-1.34923305  0.85130887]
 [-2.2529188   0.5065749 ]
 [ 1.78142948 -0.20040642]
 [-0.26532096 -1.83611671]
 [ 0.51163546  0.77469408]
 [ 0.69924102  0.22521272]]
step  1
[[-0.42501613 -0.25047283]
 [-1.70571528  0.1886584 ]
 [ 1.74723308 -0.24772639]
 [-1.04767373  0.08129321]
 [-1.34923305  0.85130887]
 [-2.2529188   0.5065749 ]
 [ 1.78142948 -0.20040642]
 [-0.26532096 -1.83611671]
 [ 0.51163546  0.77469408]
 [ 0.69924102  0.22521272]]
step  2
[[-0.43913007 -0.23199931]
 [-1.68544384  0.21036263]
 [ 3.44887912  2.13544771]
 [-1.05350331  0.09035493]
 [-1.35199603  0.81216234]
 [-2.20892077  0.49382185]
 [ 0.04637961 -2.57352848]
 [-0.2651313  -1.82191578]
 [ 0.51428079  0.73475997]
 [ 0.68824688  0.24355397]]
step  3
[[-0.46735796 -0.19505225]
 [-1.64490096  0.2537711 ]
 [ 6.85217119  6.9017959 ]
 [-1.06516246  0.10847836]
 [-1.35752199  0.73386929]
 [-2.12092469  0.468

step  27
[[  -9.49139892    4.14374676]
 [  15.86399002   -2.50095222]
 [  88.41548406  121.21670265]
 [  -4.9854994     4.32641256]
 [ -17.23319758    0.8298911 ]
 [  20.63547638   -4.66984717]
 [ -86.85706096 -120.6746867 ]
 [  -1.04117968    1.34839028]
 [  -0.81511824    5.66727398]
 [  -6.79783461   -9.59391142]]
step  28
[[  -9.9284557     4.30664892]
 [  16.68052506   -2.68154891]
 [  91.81379711  125.97963313]
 [  -5.14803931    4.55103418]
 [ -17.96752314    0.88748518]
 [  21.73056828   -4.89135951]
 [ -90.33329931 -125.39755006]
 [  -1.09480251    1.51542274]
 [  -0.90595362    5.92342373]
 [  -7.15315577  -10.10016959]]
step  29
[[ -10.36487036    4.46944149]
 [  17.49727325   -2.86227022]
 [  95.21210803  130.74256066]
 [  -5.31028098    4.77547047]
 [ -18.7015407     0.94512803]
 [  22.82525187   -5.11270209]
 [ -93.80953551 -130.12041036]
 [  -1.14886103    1.68320365]
 [  -0.99744432    6.17879308]
 [  -7.50843916  -10.60619489]]


KeyboardInterrupt: 

step  30
[[ -10.80071103    4.63213933]
 [  18.31421605   -3.04309962]
 [  98.61041696  135.50548545]
 [  -5.47219845    4.99973475]
 [ -19.43527436    1.002816  ]
 [  23.91956441   -5.33389546]
 [ -97.2857697  -134.84326784]
 [  -1.20333647    1.851702  ]
 [  -1.08955756    6.43341461]
 [  -7.86368877  -11.1120094 ]]
step  31
[[ -11.23603547    4.79475462]
 [  19.13133715   -3.22402342]
 [ 102.00872407  140.2684077 ]
 [  -5.63377268    5.22383956]
 [ -20.1687455     1.06054586]
 [  25.01353842   -5.55495685]
 [-100.76200204 -139.56612269]
 [  -1.25821164    2.02088885]
 [  -1.18226328    6.68731837]
 [  -8.21890794  -11.61763219]]
step  32
[[ -11.6708931     4.95729738]
 [  19.94862213   -3.40503017]
 [ 105.40702947  145.03132759]
 [  -5.79498987    5.44779667]
 [ -20.90197313    1.11831471]
 [  26.10720235   -5.77590078]
 [-104.23823265 -144.2889751 ]
 [  -1.31347072    2.19073715]
 [  -1.27553384    6.94053219]
 [  -8.57409955  -12.12307982]]
step  33
[[ -12.1053265     5.119776  ]


step  56
[[ -22.03039946    8.84792113]
 [  39.59235761   -7.76092338]
 [ 186.96603761  259.34095607]
 [  -9.55469833   10.79766353]
 [ -38.45428815    2.51210621]
 [  52.30119834  -11.0607538 ]
 [-187.66744104 -257.6369741 ]
 [  -2.72795877    6.41727769]
 [  -3.6370511    12.85932358]
 [ -17.09409562  -24.22357712]]
step  57
[[ -22.46018259    9.00981296]
 [  40.41158153   -7.94265804]
 [ 190.36432094  264.10384508]
 [  -9.70714615   11.02001848]
 [ -39.18443043    2.57037882]
 [  53.39125659  -11.28056247]
 [-191.14364924 -262.35979502]
 [  -2.78981419    6.59823618]
 [  -3.73929272   13.10074925]
 [ -17.44898266  -24.72700542]]
step  58
[[ -22.88987475    9.17169563]
 [  41.23084278   -8.12440245]
 [ 193.7626038   268.86673343]
 [  -9.85929421   11.24235272]
 [ -39.91450889    2.62866201]
 [  54.48124638  -11.50035354]
 [-194.61985696 -267.08261528]
 [  -2.85186054    6.77950275]
 [  -3.8417724    13.34184005]
 [ -17.80386411  -25.2303955 ]]
step  59
[[ -23.31947972    9.33356962]


step  82
[[ -33.18245775   13.05500365]
 [  60.90145163  -12.48823771]
 [ 275.32128629  383.17590393]
 [ -13.43027582   16.57538428]
 [ -57.42186493    4.02987179]
 [  80.6257509   -16.77161538]
 [-278.04873409 -380.43015061]
 [  -4.39066164   11.2079192 ]
 [  -6.361055     19.04218052]
 [ -26.31977851  -37.30323985]]
step  83
[[ -33.61069369   13.21675402]
 [  61.72132262  -12.67012022]
 [ 278.71956132  387.93878121]
 [ -13.57604488   16.79756346]
 [ -58.15087324    4.08833289]
 [  81.7146269   -16.99114006]
 [-281.52493383 -385.15295974]
 [  -4.45659536   11.39520797]
 [  -6.46813927   19.27660808]
 [ -26.67456948  -37.80600777]]
step  84
[[ -34.03889203   13.37850134]
 [  62.54120966  -12.85200584]
 [ 282.11783614  392.70165819]
 [ -13.72159511   17.01974547]
 [ -58.87985266    4.14679881]
 [  82.8034737   -17.21065826]
 [-285.00113335 -389.87576857]
 [  -4.52265802   11.58268752]
 [  -6.57536914   19.51082054]
 [ -27.0293581   -38.30875938]]
step  85
[[ -34.46705377   13.54024572]


In [18]:
#two_part_rk4.py - trying to get it into a class

class Particles_rk:
    def __init__(self,x,v,m):
        self.x=x.copy()
        self.v=v.copy()
        try:
            self.m=m.copy()
        except:
            self.m=m
        self.f=np.empty(x.shape)
        self.n=self.x.shape[0]
        
    def get_forces(self, soft=0.01, do_pot=False):
#         self.f[:]=0
#         nx=x.shape[0] #self.
        pot=0
        for i in range(self.n):
            for j in range(self.n):
#                 if i!=j:
                dx=self.x[:,0]-self.x[i,0]
                dy=self.x[:,1]-self.x[i,1]
                
                rsqr=dx**2+dy**2
                rsqr[rsqr<soft**2]=soft**2
                r3=1/(rsqr*np.sqrt(rsqr))
                
                fx=dx*r3
                fy=dy*r3
                self.f[i,0]=np.sum(fx)
                self.f[i,1]=np.sum(fy)
                
                if do_pot:
                    pot=pot+np.sum(1/rsqr)-1/soft**2 #extra bit is to remove self-energy
#                 self.f[:,:] = f
                
        if do_pot:
            print(pot/2)
            
    def get_derivs(self, xx):
        nn=xx.shape[0]//2
        self.x=xx[:nn,:] #np.array?
        self.v=xx[nn:,:]
        f=self.f
            
#         print(v, f)

        return np.vstack([v,f])

    def take_step_rk4(self, dt):
        self.get_forces()
        xx=np.vstack([self.x,self.v])
        k1=self.get_derivs(xx)
        k2=self.get_derivs(xx+k1*dt/2)
        k3=self.get_derivs(xx+k2*dt/2)
        k4=self.get_derivs(xx+k3*dt)

        tot=(k1+2*k2+2*k3+k4)/6

        nn=self.x.shape[0]
        
        print("tot")
        print(tot)
        
        self.x=self.x+tot[:nn,:]*dt
        self.v=self.v+tot[nn:,:]*dt
        

    def take_step_better(self, dt):
        xx=self.x+0.5*self.v*dt
        f=self.f
        vv=self.v+0.5*dt*f
        self.x=self.x+dt*vv
        self.v=self.v+dt*f
        
        print("step: ", f, vv)


In [28]:
n=2
x=np.random.randn(n,2)
v=np.random.randn(n,2)*0
m=np.ones(n)
parts=Particles_rk(x,v,m)
dt=0.1

colors = cm.rainbow(np.linspace(0, 1, n))

fig, ax = plt.subplots()

for i in range(100):
    print('step ',i)
    print(parts.x)

    for n_i in range(n):
        ax.scatter(parts.x[n_i][0], parts.x[n_i][1], color=colors[n_i])
#         ax.scatter(parts.x[n][0], parts.x[n_i][1], color='g')
#     time.sleep(0.1)
    ax.set_title("frame {}".format(i))

    plt.pause(0.01)

#     parts.take_step_rk4(dt)
    parts.take_step_better(dt)

fig.show()        

step  0
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  1
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  2
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  3
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  4
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  5
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]

KeyboardInterrupt: 

tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  13
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  14
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  15
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  16
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  17
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
st

tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  64
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  65
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  66
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  67
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
step  68
[[-2.20896852 -0.16133837]
 [ 0.10105707 -0.98067205]]
tot
[[ 0.         -0.        ]
 [ 0.         -0.        ]
 [ 0.15688207 -0.05564387]
 [-0.15688207  0.05564387]]
st

In [26]:

def get_forces(x,soft=0.01,do_pot=False):
    f=np.zeros(x.shape)
    nx=x.shape[0]
    pot=0
    for i in range(nx):
        dx=x[:,0]-x[i,0]
        dy=x[:,1]-x[i,1]
        rsqr=dx**2+dy**2
        rsqr[rsqr<soft**2]=soft**2
        r3=1/(rsqr*np.sqrt(rsqr))
        fx=dx*r3
        fy=dy*r3
        f[i,0]=np.sum(fx)
        f[i,1]=np.sum(fy)
        if do_pot:
            pot=pot+np.sum(1/rsqr)-1/soft**2 #extra bit is to remove self-energy
    if do_pot:
        return f,pot/2
    else:
        return f

def take_step_better(x,v,dt):
    xx=x+0.5*v*dt
    f=get_forces(xx)
    vv=v+0.5*dt*f
    x=x+dt*vv
    v=v+dt*f
    return x,v

def get_derivs(xx):
    nn=xx.shape[0]//2
    x=xx[:nn,:]
    v=xx[nn:,:]
    f=get_forces(x)
    
    return np.vstack([v,f])

def take_step_rk4(x,v,dt):

    xx=np.vstack([x,v])
    k1=get_derivs(xx)
    k2=get_derivs(xx+k1*dt/2)
    k3=get_derivs(xx+k2*dt/2)
    k4=get_derivs(xx+k3*dt)
    
    tot=(k1+2*k2+2*k3+k4)/6
    
    nn=x.shape[0]
    x=x+tot[:nn,:]*dt
    v=v+tot[nn:,:]*dt
    return x,v

In [24]:
x=np.zeros([2,2])
v=np.zeros([2,2])
x[0,0]=1
x[1,0]=-1
v[0,1]=0.25
v[1,1]=-0.25
v=0*v

soft=0.01
dt=soft**1.5*0.05
for i in range(1000):
    for i in range(1100):
        x,v=take_step_better(x,v,dt)
#         x,v=take_step_rk4(x,v,dt)

    f,pot=get_forces(x,do_pot=True)
    kin=np.sum(v**2)/2
    #print(kin,pot,kin-pot/2)
    
#     plt.clf() #clears prev graphs
    plt.plot(x[:,0],x[:,1],'b.')
    plt.axis([-2,2,-2,2])
    plt.pause(0.01)

KeyboardInterrupt: 

### Part 1: 
Using this code, show that a single particle starting at rest remains motionless. 

### Part 2: 
Next, show that a pair of particles placed in a circular orbit continue to orbit each other, for at least some reasonable length of time. 

### Part 3: 
Set up both periodic and non-periodic boundary conditions. Set up a problem where hundreds of thousands of particles are initially scattered randomly throughout the domain. Show the evolution with time for both periodic and non-periodic boundary conditions. Track the total energy how well is it conserved? 

### Part 4: 
In cosmology, we start the universe with a scale-invariant power spectrum, so mass fluctuations are proportional to k−3. Start with the particles on a grid, but with masses derived from a realization of k−3 and use periodic boundary conditions (although not strictly necessary, you may with to start with your particles in the center of grid cells rather than at the corners). How does your universe look now?